jobs:
- job:
  strategy:
    matrix:
      Mojave:
        IMAGE_POOL: 'macOS-10.14'
      Ubuntu-16:
        IMAGE_POOL: 'ubuntu-16.04'
  pool:
    vmImage: $(IMAGE_POOL)

  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: 'server/'
      gradleWrapperFile: 'server/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      tasks: 'assembleAndroidTest'

  -script: bin/build.sh --verify-only
   displayName: "$(IMAGE_POOL) - Verify TestServer.apk"

  # TODO: publish cucumber report
  # - server/integration-tests/test-report/*.xml
  - script: |
      cd server/integration-tests
      ./test.sh --skip-build
    displayName: "$(IMAGE_POOL) - Integration Tests"
